# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  IMAGE_BUILDER_TAG: sha-b3b7c128c6a3e3561c244b30d4534b2f065e6b91
  IMAGE_BUILDER_DIGEST: sha256:01666d15ece0e5fecb4f65b30598b20fdde84bfd4b65441f6779565dc78e0b93
  IMAGE_BUILDER: ghcr.io/osbuild/image-builder:{{.IMAGE_BUILDER_TAG}}@{{.IMAGE_BUILDER_DIGEST}}
  DISTRO: fedora-44
  ARCH: aarch64
  BLUEPRINT: '{{joinPath .ROOT_DIR "blueprint.toml"}}'
  OUTPUT_DIR: '{{joinPath .ROOT_DIR "output"}}'
  REPO_DIR: '{{joinPath .OUTPUT_DIR "repos"}}'
  PKG_REPO_DIR: '{{joinPath .REPO_DIR "ExtraPackages"}}'
  RAW_IMAGE: 'output/{{.DISTRO}}-minimal-raw-xz-{{.ARCH}}.raw.xz'

tasks:
  build:package:
    desc: Generate the PKI package and an RPM repository
    cmds:
      - goreleaser release --clean --snapshot
      - mkdir -p "{{.PKG_REPO_DIR}}"
      - cp dist/*.rpm "{{.PKG_REPO_DIR}}"
      - >-
        docker run -it --rm \
          -v "{{.PKG_REPO_DIR}}":/repo \
          quay.io/distributedci/dci-packaging-createrepo createrepo /repo
    sources:
      - .goreleaser.yaml
      - cmd/**/*.go
    generates:
      - '{{.PKG_REPO_DIR}}/repodata/repomd.xml'

  build:image:
    desc: Build the device image (plain Fedora minimal-raw)
    deps:
      - build:package
    cmds:
      - >-
        docker run -it --rm --privileged \
          -v "{{.BLUEPRINT}}":/blueprint.toml:ro \
          -v "{{.OUTPUT_DIR}}":/output \
          -v "{{.PKG_REPO_DIR}}":/repo \
          {{.IMAGE_BUILDER}} build minimal-raw \
            --arch {{.ARCH}} \
            --distro {{.DISTRO}} \
            --extra-repo file:///repo \
            --blueprint /blueprint.toml \
            --output-dir /output
    sources:
      - '{{.BLUEPRINT}}'
      - '{{.PKG_REPO_DIR}}/repodata/repomd.xml'
    generates:
      - '{{.RAW_IMAGE}}'

  write:*:
    desc: Write the device image to a disk attached to this system
    deps:
      - build:image
    vars:
      IDENTIFIER: '{{index .MATCH 0}}'
      DISK_SIZE:
        sh: diskutil info {{.IDENTIFIER}} | sed -n -e 's/^[[:space:]]*Disk Size:[[:space:]]*//p' | cut -d ' ' -f1,2
    prompt: WARNING! This command will overwrite the contents of {{.IDENTIFIER}} ({{.DISK_SIZE}}), would you like to continue?
    cmds:
      - diskutil eraseDisk "MS-DOS" DISK MBR {{.IDENTIFIER}}
      - diskutil unmountDisk force {{.IDENTIFIER}}
      - 'xzcat "{{.RAW_IMAGE}}" | sudo dd status=progress bs=4m of=/dev/r{{.IDENTIFIER}}'
      - diskutil unmountDisk {{.IDENTIFIER}}

  clean:
    desc: Remove built artifacts
    cmds:
      - 'rm -rf {{.OUTPUT_DIR}}'
